# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USZx-Q3-S5wTmVjNuTxhkPwvN7uwQZv6
"""

!pip install -q tensorflow scikit-image pandas matplotlib seaborn



import os
import time
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model

from skimage.metrics import structural_similarity as ssim

from sklearn.metrics import mean_squared_error, mean_absolute_error

print("TensorFlow version:", tf.__version__)

# Reproducibility
SEED = 42

np.random.seed(SEED)
tf.random.set_seed(SEED)
random.seed(SEED)

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)



(x_train_full, y_train_full), (x_test_full, y_test_full) = keras.datasets.mnist.load_data()

print("Original training data:", x_train_full.shape)
print("Original test data:", x_test_full.shape)



x_train_full = x_train_full.astype("float32") / 255.0
x_test_full = x_test_full.astype("float32") / 255.0

# Add channel dimension
x_train_full = np.expand_dims(x_train_full, axis=-1)
x_test_full = np.expand_dims(x_test_full, axis=-1)

print("Training shape:", x_train_full.shape)
print("Test shape:", x_test_full.shape)



N_TRAIN = 10000
N_TEST = 2000

x_train = x_train_full[:N_TRAIN]
y_train = y_train_full[:N_TRAIN]

x_test = x_test_full[:N_TEST]
y_test = y_test_full[:N_TEST]

print("Training images:", x_train.shape)
print("Test images:", x_test.shape)


plt.figure(figsize=(12, 6))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i].squeeze(), cmap="gray")
    plt.title(f"Digit: {y_train[i]}")
    plt.axis("off")

plt.suptitle("Sample MNIST Images")
plt.tight_layout()
plt.show()


def calculate_metrics(original, reconstructed):
    """
    Calculate MSE, MAE and average SSIM.
    """

    original = np.asarray(original)
    reconstructed = np.asarray(reconstructed)

    # MSE
    mse = np.mean((original - reconstructed) ** 2)

    # MAE
    mae = np.mean(np.abs(original - reconstructed))

    # SSIM for each image
    ssim_values = []

    for i in range(len(original)):
        img1 = original[i].squeeze()
        img2 = reconstructed[i].squeeze()

        score = ssim(
            img1,
            img2,
            data_range=1.0
        )

        ssim_values.append(score)

    mean_ssim = np.mean(ssim_values)

    return mse, mae, mean_ssim


def per_image_mse(original, reconstructed):
    """
    Reconstruction error for every image.
    """

    errors = np.mean(
        (original - reconstructed) ** 2,
        axis=(1, 2, 3)
    )

    return errors

x_train_flat = x_train.reshape(len(x_train), 784)
x_test_flat = x_test.reshape(len(x_test), 784)

print("Flattened training shape:", x_train_flat.shape)
print("Flattened test shape:", x_test_flat.shape)



def build_fc_autoencoder(latent_dim=16):

    # Input
    input_layer = keras.Input(shape=(784,))

    # Encoder
    x = layers.Dense(128, activation="relu")(input_layer)
    x = layers.Dense(32, activation="relu")(x)

    # Latent representation
    latent = layers.Dense(
        latent_dim,
        activation="relu",
        name="latent"
    )(x)

    # Decoder
    x = layers.Dense(32, activation="relu")(latent)
    x = layers.Dense(128, activation="relu")(x)

    output = layers.Dense(
        784,
        activation="sigmoid"
    )(x)

    autoencoder = Model(
        input_layer,
        output,
        name="Fully_Connected_Autoencoder"
    )

    encoder = Model(
        input_layer,
        latent,
        name="FC_Encoder"
    )

    return autoencoder, encoder



fc_ae, fc_encoder = build_fc_autoencoder(latent_dim=16)

fc_ae.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="binary_crossentropy"
)

fc_ae.summary()


start_time = time.time()

history_fc = fc_ae.fit(
    x_train_flat,
    x_train_flat,
    epochs=20,
    batch_size=128,
    validation_data=(x_test_flat, x_test_flat),
    verbose=1
)

fc_time = time.time() - start_time

print("FC Autoencoder training time:", fc_time, "seconds")


plt.figure(figsize=(10, 6))

plt.plot(
    history_fc.history["loss"],
    label="Training Loss"
)

plt.plot(
    history_fc.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Reconstruction Loss")
plt.title("FC Autoencoder Training and Validation Loss")
plt.legend()
plt.show()



fc_reconstructed_flat = fc_ae.predict(
    x_test_flat,
    verbose=0
)

fc_reconstructed = fc_reconstructed_flat.reshape(
    -1, 28, 28, 1
)

print("Reconstructed shape:", fc_reconstructed.shape)


plt.figure(figsize=(15, 6))

for i in range(10):

    # Original
    plt.subplot(2, 10, i + 1)
    plt.imshow(x_test[i].squeeze(), cmap="gray")
    plt.title("Original")
    plt.axis("off")

    # Reconstruction
    plt.subplot(2, 10, i + 11)
    plt.imshow(fc_reconstructed[i].squeeze(), cmap="gray")
    plt.title("Reconstructed")
    plt.axis("off")

plt.suptitle("Fully Connected Autoencoder")
plt.tight_layout()
plt.show()



fc_mse, fc_mae, fc_ssim = calculate_metrics(
    x_test,
    fc_reconstructed
)

print("FC Autoencoder Results")
print("----------------------")
print("MSE :", fc_mse)
print("MAE :", fc_mae)
print("SSIM:", fc_ssim)



fc_latent = fc_encoder.predict(
    x_test_flat,
    verbose=0
)

print("Latent representation shape:", fc_latent.shape)



plt.figure(figsize=(10, 8))

scatter = plt.scatter(
    fc_latent[:, 0],
    fc_latent[:, 1],
    c=y_test,
    cmap="tab10",
    s=10,
    alpha=0.7
)

plt.colorbar(scatter, label="Digit")
plt.xlabel("Latent Dimension 1")
plt.ylabel("Latent Dimension 2")
plt.title("FC Autoencoder Latent Representation")
plt.show()



def build_conv_autoencoder():

    input_layer = keras.Input(
        shape=(28, 28, 1)
    )

    # --------------------
    # Encoder
    # --------------------

    x = layers.Conv2D(
        32,
        3,
        activation="relu",
        padding="same"
    )(input_layer)

    x = layers.MaxPooling2D(
        2,
        padding="same"
    )(x)

    x = layers.Conv2D(
        64,
        3,
        activation="relu",
        padding="same"
    )(x)

    x = layers.MaxPooling2D(
        2,
        padding="same"
    )(x)

    x = layers.Conv2D(
        64,
        3,
        activation="relu",
        padding="same"
    )(x)

    # Latent feature map
    latent = x

    # --------------------
    # Decoder
    # --------------------

    x = layers.UpSampling2D(2)(latent)

    x = layers.Conv2D(
        32,
        3,
        activation="relu",
        padding="same"
    )(x)

    x = layers.UpSampling2D(2)(x)

    output = layers.Conv2D(
        1,
        3,
        activation="sigmoid",
        padding="same"
    )(x)

    autoencoder = Model(
        input_layer,
        output,
        name="Convolutional_Autoencoder"
    )

    encoder = Model(
        input_layer,
        latent,
        name="Conv_Encoder"
    )

    return autoencoder, encoder



conv_ae, conv_encoder = build_conv_autoencoder()

conv_ae.compile(
    optimizer=keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="binary_crossentropy"
)

conv_ae.summary()



start_time = time.time()

history_conv = conv_ae.fit(
    x_train,
    x_train,
    epochs=20,
    batch_size=128,
    validation_data=(x_test, x_test),
    verbose=1
)

conv_time = time.time() - start_time

print("Convolutional AE training time:", conv_time)



plt.figure(figsize=(10, 6))

plt.plot(
    history_conv.history["loss"],
    label="Training Loss"
)

plt.plot(
    history_conv.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Reconstruction Loss")
plt.title("Convolutional Autoencoder Loss")
plt.legend()
plt.show()



conv_reconstructed = conv_ae.predict(
    x_test,
    verbose=0
)

print(conv_reconstructed.shape)


conv_mse, conv_mae, conv_ssim = calculate_metrics(
    x_test,
    conv_reconstructed
)

print("Convolutional Autoencoder Results")
print("----------------------------------")
print("MSE :", conv_mse)
print("MAE :", conv_mae)
print("SSIM:", conv_ssim)



plt.figure(figsize=(15, 9))

for i in range(10):

    # Original
    plt.subplot(3, 10, i + 1)
    plt.imshow(x_test[i].squeeze(), cmap="gray")
    plt.title("Original")
    plt.axis("off")

    # FC
    plt.subplot(3, 10, i + 11)
    plt.imshow(fc_reconstructed[i].squeeze(), cmap="gray")
    plt.title("FC-AE")
    plt.axis("off")

    # Conv
    plt.subplot(3, 10, i + 21)
    plt.imshow(conv_reconstructed[i].squeeze(), cmap="gray")
    plt.title("CAE")
    plt.axis("off")

plt.suptitle("FC Autoencoder vs Convolutional Autoencoder")
plt.tight_layout()
plt.show()



fc_params = fc_ae.count_params()
conv_params = conv_ae.count_params()

comparison = pd.DataFrame({
    "Model": [
        "Fully Connected AE",
        "Convolutional AE"
    ],
    "MSE": [
        fc_mse,
        conv_mse
    ],
    "MAE": [
        fc_mae,
        conv_mae
    ],
    "SSIM": [
        fc_ssim,
        conv_ssim
    ],
    "Parameters": [
        fc_params,
        conv_params
    ],
    "Training Time (sec)": [
        fc_time,
        conv_time
    ]
})

comparison

def add_gaussian_noise(images, sigma):

    noise = np.random.normal(
        loc=0.0,
        scale=sigma,
        size=images.shape
    )

    noisy_images = images + noise

    noisy_images = np.clip(
        noisy_images,
        0.0,
        1.0
    )

    return noisy_images.astype("float32")



sigmas = [0.1, 0.2, 0.3]

plt.figure(figsize=(12, 8))

for row, sigma in enumerate(sigmas):

    noisy = add_gaussian_noise(
        x_test[:5],
        sigma
    )

    for col in range(5):

        plt.subplot(3, 5, row * 5 + col + 1)

        plt.imshow(
            noisy[col].squeeze(),
            cmap="gray"
        )

        plt.title(f"sigma={sigma}")
        plt.axis("off")

plt.tight_layout()
plt.show()



def add_salt_pepper_noise(images, probability):

    noisy = images.copy()

    random_values = np.random.rand(*images.shape)

    # Pepper
    noisy[random_values < probability / 2] = 0.0

    # Salt
    noisy[
        (random_values >= probability / 2) &
        (random_values < probability)
    ] = 1.0

    return noisy.astype("float32")



probabilities = [0.05, 0.10, 0.20]

plt.figure(figsize=(12, 8))

for row, p in enumerate(probabilities):

    noisy = add_salt_pepper_noise(
        x_test[:5],
        p
    )

    for col in range(5):

        plt.subplot(3, 5, row * 5 + col + 1)

        plt.imshow(
            noisy[col].squeeze(),
            cmap="gray"
        )

        plt.title(f"p={p}")
        plt.axis("off")

plt.tight_layout()
plt.show()


denoising_ae, denoising_encoder = build_conv_autoencoder()

denoising_ae.compile(
    optimizer=keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="binary_crossentropy"
)

denoising_ae.summary()


NOISE_SIGMA = 0.2

x_train_noisy = add_gaussian_noise(
    x_train,
    NOISE_SIGMA
)

x_test_noisy = add_gaussian_noise(
    x_test,
    NOISE_SIGMA
)

print(x_train_noisy.shape)


start_time = time.time()

history_denoising = denoising_ae.fit(
    x_train_noisy,
    x_train,
    epochs=20,
    batch_size=128,
    validation_data=(x_test_noisy, x_test),
    verbose=1
)

denoising_time = time.time() - start_time

print(
    "Denoising AE training time:",
    denoising_time
)


plt.figure(figsize=(10, 6))

plt.plot(
    history_denoising.history["loss"],
    label="Training Loss"
)

plt.plot(
    history_denoising.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Reconstruction Loss")
plt.title("Denoising Autoencoder Loss")
plt.legend()
plt.show()


denoised_images = denoising_ae.predict(
    x_test_noisy,
    verbose=0
)


plt.figure(figsize=(15, 9))

for i in range(10):

    # Clean
    plt.subplot(3, 10, i + 1)
    plt.imshow(
        x_test[i].squeeze(),
        cmap="gray"
    )
    plt.title("Clean")
    plt.axis("off")

    # Noisy
    plt.subplot(3, 10, i + 11)
    plt.imshow(
        x_test_noisy[i].squeeze(),
        cmap="gray"
    )
    plt.title("Noisy")
    plt.axis("off")

    # Denoised
    plt.subplot(3, 10, i + 21)
    plt.imshow(
        denoised_images[i].squeeze(),
        cmap="gray"
    )
    plt.title("Denoised")
    plt.axis("off")

plt.suptitle("Denoising Autoencoder")
plt.tight_layout()
plt.show()


denoise_mse, denoise_mae, denoise_ssim = calculate_metrics(
    x_test,
    denoised_images
)

print("Denoising CAE")
print("-------------")
print("MSE :", denoise_mse)
print("MAE :", denoise_mae)
print("SSIM:", denoise_ssim)



noise_results = []

for sigma in [0.1, 0.2, 0.3]:

    noisy_test = add_gaussian_noise(
        x_test,
        sigma
    )

    reconstructed = denoising_ae.predict(
        noisy_test,
        verbose=0
    )

    mse, mae, ssim_value = calculate_metrics(
        x_test,
        reconstructed
    )

    noise_results.append({
        "Noise Level (sigma)": sigma,
        "MSE": mse,
        "MAE": mae,
        "SSIM": ssim_value
    })

noise_df = pd.DataFrame(noise_results)

noise_df


plt.figure(figsize=(8, 5))

plt.plot(
    noise_df["Noise Level (sigma)"],
    noise_df["MSE"],
    marker="o"
)

plt.xlabel("Gaussian Noise Sigma")
plt.ylabel("MSE")
plt.title("Noise Level vs MSE")
plt.show()



plt.figure(figsize=(8, 5))

plt.plot(
    noise_df["Noise Level (sigma)"],
    noise_df["MAE"],
    marker="o",
    color="orange"
)

plt.xlabel("Gaussian Noise Sigma")
plt.ylabel("MAE")
plt.title("Noise Level vs MAE")
plt.show()

plt.figure(figsize=(8, 5))

plt.plot(
    noise_df["Noise Level (sigma)"],
    noise_df["SSIM"],
    marker="o",
    color="green"
)

plt.xlabel("Gaussian Noise Sigma")
plt.ylabel("SSIM")
plt.title("Noise Level vs SSIM")
plt.show()



sp_results = []

for p in [0.05, 0.10, 0.20]:

    noisy_test = add_salt_pepper_noise(
        x_test,
        p
    )

    reconstructed = denoising_ae.predict(
        noisy_test,
        verbose=0
    )

    mse, mae, ssim_value = calculate_metrics(
        x_test,
        reconstructed
    )

    sp_results.append({
        "Salt-Pepper Probability": p,
        "MSE": mse,
        "MAE": mae,
        "SSIM": ssim_value
    })

sp_df = pd.DataFrame(sp_results)

sp_df

# ============================================================
# CELL 42: VAE PARAMETERS
# ============================================================

LATENT_DIM = 2

# ============================================================
# CELL 43: SAMPLING LAYER
# ============================================================

class Sampling(layers.Layer):

    def call(self, inputs):

        z_mean, z_log_var = inputs

        batch = tf.shape(z_mean)[0]

        dim = tf.shape(z_mean)[1]

        epsilon = tf.random.normal(
            shape=(batch, dim)
        )

        return (
            z_mean +
            tf.exp(0.5 * z_log_var) *
            epsilon
        )

# ============================================================
# CELL 44: VAE ENCODER
# ============================================================

def build_vae_encoder(latent_dim=2):

    encoder_inputs = keras.Input(
        shape=(28, 28, 1),
        name="encoder_input"
    )

    x = layers.Conv2D(
        32,
        3,
        strides=2,
        padding="same",
        activation="relu"
    )(encoder_inputs)

    x = layers.Conv2D(
        64,
        3,
        strides=2,
        padding="same",
        activation="relu"
    )(x)

    x = layers.Flatten()(x)

    x = layers.Dense(128, activation="relu")(x)

    z_mean = layers.Dense(
        latent_dim,
        name="z_mean"
    )(x)

    z_log_var = layers.Dense(
        latent_dim,
        name="z_log_var"
    )(x)

    z = Sampling()([
        z_mean,
        z_log_var
    ])

    encoder = Model(
        encoder_inputs,
        [z_mean, z_log_var, z],
        name="VAE_Encoder"
    )

    return encoder

# ============================================================
# CELL 45: VAE DECODER
# ============================================================

def build_vae_decoder(latent_dim=2):

    latent_inputs = keras.Input(
        shape=(latent_dim,),
        name="z_sampling"
    )

    x = layers.Dense(
        7 * 7 * 64,
        activation="relu"
    )(latent_inputs)

    x = layers.Reshape(
        (7, 7, 64)
    )(x)

    x = layers.Conv2DTranspose(
        64,
        3,
        strides=2,
        padding="same",
        activation="relu"
    )(x)

    x = layers.Conv2DTranspose(
        32,
        3,
        strides=2,
        padding="same",
        activation="relu"
    )(x)

    decoder_outputs = layers.Conv2DTranspose(
        1,
        3,
        padding="same",
        activation="sigmoid"
    )(x)

    decoder = Model(
        latent_inputs,
        decoder_outputs,
        name="VAE_Decoder"
    )

    return decoder

# ============================================================
# CELL 46: BUILD VAE
# ============================================================

vae_encoder = build_vae_encoder(
    LATENT_DIM
)

vae_decoder = build_vae_decoder(
    LATENT_DIM
)

vae_encoder.summary()
vae_decoder.summary()

# ============================================================
# CELL 47: VAE MODEL
# ============================================================

class VAE(keras.Model):

    def __init__(
        self,
        encoder,
        decoder,
        **kwargs
    ):
        super().__init__(**kwargs)

        self.encoder = encoder
        self.decoder = decoder

        self.total_loss_tracker = keras.metrics.Mean(
            name="total_loss"
        )

        self.reconstruction_loss_tracker = keras.metrics.Mean(
            name="reconstruction_loss"
        )

        self.kl_loss_tracker = keras.metrics.Mean(
            name="kl_loss"
        )

    @property
    def metrics(self):

        return [
            self.total_loss_tracker,
            self.reconstruction_loss_tracker,
            self.kl_loss_tracker
        ]

    def train_step(self, data):

        if isinstance(data, tuple):
            data = data[0]

        with tf.GradientTape() as tape:

            z_mean, z_log_var, z = self.encoder(data)

            reconstruction = self.decoder(z)

            # Reconstruction loss
            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(
                    keras.losses.binary_crossentropy(
                        data,
                        reconstruction
                    ),
                    axis=(1, 2)
                )
            )

            # KL divergence
            kl_loss = -0.5 * tf.reduce_mean(
                tf.reduce_sum(
                    1 +
                    z_log_var -
                    tf.square(z_mean) -
                    tf.exp(z_log_var),
                    axis=1
                )
            )

            total_loss = (
                reconstruction_loss +
                kl_loss
            )

        grads = tape.gradient(
            total_loss,
            self.trainable_weights
        )

        self.optimizer.apply_gradients(
            zip(
                grads,
                self.trainable_weights
            )
        )

        self.total_loss_tracker.update_state(
            total_loss
        )

        self.reconstruction_loss_tracker.update_state(
            reconstruction_loss
        )

        self.kl_loss_tracker.update_state(
            kl_loss
        )

        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction_loss":
                self.reconstruction_loss_tracker.result(),
            "kl_loss":
                self.kl_loss_tracker.result()
        }

    def test_step(self, data):

        if isinstance(data, tuple):
            data = data[0]

        z_mean, z_log_var, z = self.encoder(data)

        reconstruction = self.decoder(z)

        reconstruction_loss = tf.reduce_mean(
            tf.reduce_sum(
                keras.losses.binary_crossentropy(
                    data,
                    reconstruction
                ),
                axis=(1, 2)
            )
        )

        kl_loss = -0.5 * tf.reduce_mean(
            tf.reduce_sum(
                1 +
                z_log_var -
                tf.square(z_mean) -
                tf.exp(z_log_var),
                axis=1
            )
        )

        total_loss = (
            reconstruction_loss +
            kl_loss
        )

        self.total_loss_tracker.update_state(
            total_loss
        )

        self.reconstruction_loss_tracker.update_state(
            reconstruction_loss
        )

        self.kl_loss_tracker.update_state(
            kl_loss
        )

        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction_loss":
                self.reconstruction_loss_tracker.result(),
            "kl_loss":
                self.kl_loss_tracker.result()
        }

# ============================================================
# CELL 48: TRAIN VAE
# ============================================================

vae = VAE(
    vae_encoder,
    vae_decoder,
    name="VAE"
)

vae.compile(
    optimizer=keras.optimizers.Adam(
        learning_rate=0.001
    )
)

start_time = time.time()

history_vae = vae.fit(
    x_train,
    epochs=20,
    batch_size=128,
    validation_data=(x_test, None),
    verbose=1
)

vae_time = time.time() - start_time

print("VAE training time:", vae_time)

# ============================================================
# CELL 49: VAE LOSS CURVES
# ============================================================

plt.figure(figsize=(12, 8))

plt.subplot(3, 1, 1)

plt.plot(
    history_vae.history["loss"],
    label="Training"
)

plt.xlabel("Epoch")
plt.ylabel("Total Loss")
plt.title("VAE Total Loss")
plt.legend()


plt.subplot(3, 1, 2)

plt.plot(
    history_vae.history["reconstruction_loss"],
    label="Training Reconstruction Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Reconstruction Loss")
plt.title("VAE Reconstruction Loss")
plt.legend()


plt.subplot(3, 1, 3)

plt.plot(
    history_vae.history["kl_loss"],
    label="Training KL Loss"
)

plt.xlabel("Epoch")
plt.ylabel("KL Loss")
plt.title("VAE KL Divergence")
plt.legend()

plt.tight_layout()
plt.show()

# ============================================================
# CELL 50: VAE RECONSTRUCTION
# ============================================================

z_mean, z_log_var, z = vae_encoder.predict(
    x_test,
    verbose=0
)

vae_reconstructed = vae_decoder.predict(
    z,
    verbose=0
)

print("VAE reconstruction shape:")
print(vae_reconstructed.shape)

# ============================================================
# CELL 51: VAE IMAGE METRICS
# ============================================================

vae_mse, vae_mae, vae_ssim = calculate_metrics(
    x_test,
    vae_reconstructed
)

print("VAE Image Reconstruction")
print("-------------------------")
print("MSE :", vae_mse)
print("MAE :", vae_mae)
print("SSIM:", vae_ssim)

# ============================================================
# CELL 52: VAE LATENT SPACE
# ============================================================

plt.figure(figsize=(10, 8))

scatter = plt.scatter(
    z_mean[:, 0],
    z_mean[:, 1],
    c=y_test,
    cmap="tab10",
    s=10,
    alpha=0.7
)

plt.colorbar(
    scatter,
    label="Digit"
)

plt.xlabel("z1")
plt.ylabel("z2")

plt.title(
    "2D VAE Latent Space"
)

plt.show()

# ============================================================
# CELL 53: GENERATE NEW VAE IMAGES
# ============================================================

num_samples = 25

random_latent_vectors = np.random.normal(
    size=(num_samples, LATENT_DIM)
)

generated_images = vae_decoder.predict(
    random_latent_vectors,
    verbose=0
)

print(generated_images.shape)

# ============================================================
# CELL 54: DISPLAY 25 GENERATED IMAGES
# ============================================================

plt.figure(figsize=(10, 10))

for i in range(25):

    plt.subplot(5, 5, i + 1)

    plt.imshow(
        generated_images[i].squeeze(),
        cmap="gray"
    )

    plt.axis("off")

plt.suptitle(
    "25 Randomly Generated VAE Images"
)

plt.tight_layout()
plt.show()

# ============================================================
# CELL 55: SELECT TWO LATENT VECTORS
# ============================================================

# Select two test images
index_a = 0
index_b = 1

z_a = z_mean[index_a]
z_b = z_mean[index_b]

print("Digit A:", y_test[index_a])
print("Digit B:", y_test[index_b])

print("zA:", z_a)
print("zB:", z_b)

# ============================================================
# CELL 56: LATENT INTERPOLATION
# ============================================================

alphas = np.linspace(
    0,
    1,
    11
)

interpolated_vectors = []

for alpha in alphas:

    z_interpolated = (
        (1 - alpha) * z_a +
        alpha * z_b
    )

    interpolated_vectors.append(
        z_interpolated
    )

interpolated_vectors = np.array(
    interpolated_vectors
)

interpolated_images = vae_decoder.predict(
    interpolated_vectors,
    verbose=0
)

# ============================================================
# CELL 57: DISPLAY INTERPOLATION
# ============================================================

plt.figure(figsize=(20, 3))

for i in range(len(alphas)):

    plt.subplot(1, 11, i + 1)

    plt.imshow(
        interpolated_images[i].squeeze(),
        cmap="gray"
    )

    plt.title(
        f"{alphas[i]:.1f}"
    )

    plt.axis("off")

plt.suptitle(
    f"Latent Interpolation: Digit {y_test[index_a]} → Digit {y_test[index_b]}"
)

plt.tight_layout()
plt.show()

# ============================================================
# CELL 58: VAE TEST LOSS
# ============================================================

vae_test_results = vae.evaluate(
    x_test,
    verbose=1,
    return_dict=True
)

print("\nVAE Test Results")
print("----------------")
print(
    "Total Loss:",
    vae_test_results["loss"]
)

print(
    "Reconstruction Loss:",
    vae_test_results["reconstruction_loss"]
)

print(
    "KL Loss:",
    vae_test_results["kl_loss"]
)

# ============================================================
# CELL 59: RECONSTRUCTION ERRORS
# ============================================================

fc_errors = per_image_mse(
    x_test,
    fc_reconstructed
)

conv_errors = per_image_mse(
    x_test,
    conv_reconstructed
)

denoising_errors = per_image_mse(
    x_test,
    denoised_images
)

vae_errors = per_image_mse(
    x_test,
    vae_reconstructed
)

print("Mean FC error:", np.mean(fc_errors))
print("Mean CAE error:", np.mean(conv_errors))
print("Mean Denoising error:", np.mean(denoising_errors))
print("Mean VAE error:", np.mean(vae_errors))

# ============================================================
# CELL 60: ERROR DISTRIBUTION
# ============================================================

plt.figure(figsize=(10, 6))

plt.hist(
    fc_errors,
    bins=50,
    alpha=0.7,
    color="blue"
)

plt.xlabel("Per-image Reconstruction MSE")
plt.ylabel("Number of Images")
plt.title(
    "Distribution of FC Autoencoder Reconstruction Errors"
)

plt.show()

# ============================================================
# CELL 61: ALL MODEL ERROR DISTRIBUTIONS
# ============================================================

plt.figure(figsize=(12, 7))

plt.hist(
    fc_errors,
    bins=50,
    alpha=0.4,
    label="FC AE"
)

plt.hist(
    conv_errors,
    bins=50,
    alpha=0.4,
    label="CAE"
)

plt.hist(
    denoising_errors,
    bins=50,
    alpha=0.4,
    label="Denoising CAE"
)

plt.hist(
    vae_errors,
    bins=50,
    alpha=0.4,
    label="VAE"
)

plt.xlabel("Per-image MSE")
plt.ylabel("Frequency")
plt.title("Reconstruction Error Distributions")
plt.legend()

plt.show()

# ============================================================
# CELL 62: FIVE HIGH-ERROR IMAGES
# ============================================================

highest_error_indices = np.argsort(
    fc_errors
)[-5:][::-1]

print("Highest error indices:")
print(highest_error_indices)

print("\nCorresponding digits:")

for idx in highest_error_indices:
    print(
        "Index:",
        idx,
        "Digit:",
        y_test[idx],
        "Error:",
        fc_errors[idx]
    )

# ============================================================
# CELL 63: HIGH-ERROR IMAGE ANALYSIS
# ============================================================

plt.figure(figsize=(15, 6))

for i, idx in enumerate(
    highest_error_indices
):

    # Original
    plt.subplot(2, 5, i + 1)

    plt.imshow(
        x_test[idx].squeeze(),
        cmap="gray"
    )

    plt.title(
        f"Original\nDigit={y_test[idx]}"
    )

    plt.axis("off")

    # Reconstruction
    plt.subplot(2, 5, i + 6)

    plt.imshow(
        fc_reconstructed[idx].squeeze(),
        cmap="gray"
    )

    plt.title(
        f"Reconstruction\nError={fc_errors[idx]:.4f}"
    )

    plt.axis("off")

plt.suptitle(
    "Five Highest Reconstruction-Error Images"
)

plt.tight_layout()
plt.show()

# ============================================================
# VAE PARAMETER COUNT - CORRECTED
# ============================================================

vae_encoder_params = vae_encoder.count_params()
vae_decoder_params = vae_decoder.count_params()

vae_params = (
    vae_encoder_params +
    vae_decoder_params
)

print("VAE Encoder Parameters:", vae_encoder_params)
print("VAE Decoder Parameters:", vae_decoder_params)
print("Total VAE Parameters:", vae_params)

# ============================================================
# FINAL BLOCK - CREATE + DISPLAY + SAVE ALL RESULTS
# ============================================================

import os
import pandas as pd

# Create results folder
os.makedirs("autoencoder_results", exist_ok=True)


# ------------------------------------------------------------
# 1. VAE parameter count
# ------------------------------------------------------------

vae_encoder_params = vae_encoder.count_params()
vae_decoder_params = vae_decoder.count_params()

vae_params = (
    vae_encoder_params +
    vae_decoder_params
)

print("VAE Encoder Parameters:", vae_encoder_params)
print("VAE Decoder Parameters:", vae_decoder_params)
print("Total VAE Parameters:", vae_params)


# ------------------------------------------------------------
# 2. FINAL CONSOLIDATED TABLE
# ------------------------------------------------------------

final_results = pd.DataFrame({

    "Model": [
        "FC Autoencoder",
        "Convolutional Autoencoder",
        "Denoising CAE",
        "VAE"
    ],

    "MSE": [
        fc_mse,
        conv_mse,
        denoise_mse,
        vae_mse
    ],

    "MAE": [
        fc_mae,
        conv_mae,
        denoise_mae,
        vae_mae
    ],

    "SSIM": [
        fc_ssim,
        conv_ssim,
        denoise_ssim,
        vae_ssim
    ],

    "Parameters": [
        fc_ae.count_params(),
        conv_ae.count_params(),
        denoising_ae.count_params(),
        vae_params
    ],

    "Training Time (sec)": [
        fc_time,
        conv_time,
        denoising_time,
        vae_time
    ]
})


# ------------------------------------------------------------
# 3. DISPLAY FINAL TABLE
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("FINAL CONSOLIDATED RESULTS")
print("=" * 90)

display(final_results)


# ------------------------------------------------------------
# 4. VAE RESULTS TABLE
# ------------------------------------------------------------

vae_results_table = pd.DataFrame({

    "Metric": [
        "Reconstruction Loss",
        "KL Loss",
        "Total Loss",
        "Test MSE",
        "Test MAE",
        "Mean SSIM"
    ],

    "Value": [
        vae_test_results["reconstruction_loss"],
        vae_test_results["kl_loss"],
        vae_test_results["loss"],
        vae_mse,
        vae_mae,
        vae_ssim
    ]
})

print("\n" + "=" * 90)
print("VAE RESULTS")
print("=" * 90)

display(vae_results_table)


# ------------------------------------------------------------
# 5. SAVE FINAL TABLE
# ------------------------------------------------------------

final_results.to_csv(
    "autoencoder_results/final_results.csv",
    index=False
)

vae_results_table.to_csv(
    "autoencoder_results/vae_results.csv",
    index=False
)


# ------------------------------------------------------------
# 6. SAVE OTHER RESULT TABLES
# ------------------------------------------------------------

# Gaussian noise
if "noise_df" in globals():
    noise_df.to_csv(
        "autoencoder_results/gaussian_noise_results.csv",
        index=False
    )

# Salt and pepper
if "sp_df" in globals():
    sp_df.to_csv(
        "autoencoder_results/salt_pepper_results.csv",
        index=False
    )

# FC latent dimension study
if "latent_df" in globals():
    latent_df.to_csv(
        "autoencoder_results/fc_latent_dimension_results.csv",
        index=False
    )

# CAE latent dimension study
if "conv_latent_df" in globals():
    conv_latent_df.to_csv(
        "autoencoder_results/cae_latent_dimension_results.csv",
        index=False
    )


# ------------------------------------------------------------
# 7. PRINT VALUES FOR REPORT
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("VALUES FOR REPORT")
print("=" * 90)

print("\nFC AUTOENCODER")
print("MSE        :", fc_mse)
print("MAE        :", fc_mae)
print("SSIM       :", fc_ssim)
print("Parameters :", fc_ae.count_params())
print("Time       :", fc_time, "seconds")


print("\nCONVOLUTIONAL AUTOENCODER")
print("MSE        :", conv_mse)
print("MAE        :", conv_mae)
print("SSIM       :", conv_ssim)
print("Parameters :", conv_ae.count_params())
print("Time       :", conv_time, "seconds")


print("\nDENOISING CAE")
print("MSE        :", denoise_mse)
print("MAE        :", denoise_mae)
print("SSIM       :", denoise_ssim)
print("Parameters :", denoising_ae.count_params())
print("Time       :", denoising_time, "seconds")


print("\nVAE")
print(
    "Reconstruction Loss :",
    vae_test_results["reconstruction_loss"]
)

print(
    "KL Loss             :",
    vae_test_results["kl_loss"]
)

print(
    "Total Loss          :",
    vae_test_results["loss"]
)

print("MSE                 :", vae_mse)
print("MAE                 :", vae_mae)
print("SSIM                :", vae_ssim)
print("Parameters          :", vae_params)
print("Time                :", vae_time, "seconds")

# ============================================================
# CELL 66: VAE RESULTS TABLE
# ============================================================

vae_results_table = pd.DataFrame({
    "Metric": [
        "Reconstruction Loss",
        "KL Loss",
        "Total Loss",
        "Test MSE",
        "Test MAE",
        "Mean SSIM"
    ],

    "Value": [
        vae_test_results["reconstruction_loss"],
        vae_test_results["kl_loss"],
        vae_test_results["loss"],
        vae_mse,
        vae_mae,
        vae_ssim
    ]
})

vae_results_table

# ============================================================
# CELL 67: LATENT DIMENSION STUDY
# ============================================================

latent_dimensions = [2, 8, 16, 32]

latent_results = []

LATENT_EPOCHS = 10

for latent_dim in latent_dimensions:

    print("\n================================")
    print("Training latent dimension:", latent_dim)
    print("================================")

    model, encoder = build_fc_autoencoder(
        latent_dim=latent_dim
    )

    model.compile(
        optimizer=keras.optimizers.Adam(
            learning_rate=0.001
        ),
        loss="binary_crossentropy"
    )

    start = time.time()

    model.fit(
        x_train_flat,
        x_train_flat,
        epochs=LATENT_EPOCHS,
        batch_size=128,
        validation_data=(
            x_test_flat,
            x_test_flat
        ),
        verbose=0
    )

    training_time = time.time() - start

    reconstruction_flat = model.predict(
        x_test_flat,
        verbose=0
    )

    reconstruction = reconstruction_flat.reshape(
        -1, 28, 28, 1
    )

    mse, mae, ssim_value = calculate_metrics(
        x_test,
        reconstruction
    )

    latent_results.append({
        "Latent Dimension": latent_dim,
        "MSE": mse,
        "MAE": mae,
        "SSIM": ssim_value,
        "Parameters": model.count_params(),
        "Training Time": training_time
    })

latent_df = pd.DataFrame(
    latent_results
)

latent_df

# ============================================================
# CELL 68: LATENT DIMENSION VS MSE
# ============================================================

plt.figure(figsize=(9, 6))

plt.plot(
    latent_df["Latent Dimension"],
    latent_df["MSE"],
    marker="o",
    linewidth=2
)

plt.xlabel("Latent Dimension")
plt.ylabel("Reconstruction MSE")
plt.title(
    "Effect of Latent Dimension on Reconstruction MSE"
)

plt.xticks(latent_dimensions)

plt.show()

# ============================================================
# CELL 69: LATENT DIMENSION VS SSIM
# ============================================================

plt.figure(figsize=(9, 6))

plt.plot(
    latent_df["Latent Dimension"],
    latent_df["SSIM"],
    marker="o",
    color="green",
    linewidth=2
)

plt.xlabel("Latent Dimension")
plt.ylabel("SSIM")
plt.title(
    "Effect of Latent Dimension on SSIM"
)

plt.xticks(latent_dimensions)

plt.show()

# ============================================================
# CELL 70: CONVOLUTIONAL AE WITH CONTROLLED LATENT DIMENSION
# ============================================================

def build_conv_latent_autoencoder(latent_dim):

    input_layer = keras.Input(
        shape=(28, 28, 1)
    )

    # Encoder
    x = layers.Conv2D(
        32,
        3,
        activation="relu",
        padding="same"
    )(input_layer)

    x = layers.MaxPooling2D(
        2,
        padding="same"
    )(x)

    x = layers.Conv2D(
        64,
        3,
        activation="relu",
        padding="same"
    )(x)

    x = layers.MaxPooling2D(
        2,
        padding="same"
    )(x)

    x = layers.Flatten()(x)

    latent = layers.Dense(
        latent_dim,
        activation="relu",
        name="latent"
    )(x)

    # Decoder
    x = layers.Dense(
        7 * 7 * 64,
        activation="relu"
    )(latent)

    x = layers.Reshape(
        (7, 7, 64)
    )(x)

    x = layers.UpSampling2D(2)(x)

    x = layers.Conv2D(
        32,
        3,
        activation="relu",
        padding="same"
    )(x)

    x = layers.UpSampling2D(2)(x)

    output = layers.Conv2D(
        1,
        3,
        activation="sigmoid",
        padding="same"
    )(x)

    model = Model(
        input_layer,
        output
    )

    return model

# ============================================================
# CELL 71: CAE LATENT DIMENSION STUDY
# ============================================================

conv_latent_dimensions = [4, 8, 16, 32]

conv_latent_results = []

for latent_dim in conv_latent_dimensions:

    print(
        "Training CAE latent dimension:",
        latent_dim
    )

    model = build_conv_latent_autoencoder(
        latent_dim
    )

    model.compile(
        optimizer=keras.optimizers.Adam(
            learning_rate=0.001
        ),
        loss="binary_crossentropy"
    )

    start = time.time()

    model.fit(
        x_train,
        x_train,
        epochs=10,
        batch_size=128,
        validation_data=(x_test, x_test),
        verbose=0
    )

    training_time = time.time() - start

    reconstructed = model.predict(
        x_test,
        verbose=0
    )

    mse, mae, ssim_value = calculate_metrics(
        x_test,
        reconstructed
    )

    conv_latent_results.append({

        "Latent Dimension": latent_dim,

        "MSE": mse,

        "MAE": mae,

        "SSIM": ssim_value,

        "Parameters": model.count_params(),

        "Training Time": training_time
    })

conv_latent_df = pd.DataFrame(
    conv_latent_results
)

conv_latent_df

# ============================================================
# CELL 72: CAE LATENT DIMENSION PLOT
# ============================================================

plt.figure(figsize=(9, 6))

plt.plot(
    conv_latent_df["Latent Dimension"],
    conv_latent_df["MSE"],
    marker="o"
)

plt.xlabel("Latent Dimension")
plt.ylabel("MSE")
plt.title(
    "CAE Latent Dimension vs Reconstruction MSE"
)

plt.xticks(conv_latent_dimensions)

plt.show()

# ============================================================
# CELL 73: CAE WITH TRANSPOSED CONVOLUTION
# ============================================================

def build_transpose_conv_autoencoder():

    input_layer = keras.Input(
        shape=(28, 28, 1)
    )

    # Encoder
    x = layers.Conv2D(
        32,
        3,
        activation="relu",
        padding="same"
    )(input_layer)

    x = layers.MaxPooling2D(
        2,
        padding="same"
    )(x)

    x = layers.Conv2D(
        64,
        3,
        activation="relu",
        padding="same"
    )(x)

    x = layers.MaxPooling2D(
        2,
        padding="same"
    )(x)

    # Decoder
    x = layers.Conv2DTranspose(
        64,
        3,
        strides=2,
        padding="same",
        activation="relu"
    )(x)

    x = layers.Conv2DTranspose(
        32,
        3,
        strides=2,
        padding="same",
        activation="relu"
    )(x)

    output = layers.Conv2D(
        1,
        3,
        activation="sigmoid",
        padding="same"
    )(x)

    model = Model(
        input_layer,
        output,
        name="Transpose_Conv_AE"
    )

    return model

# ============================================================
# CELL 74: TRAIN TRANSPOSE CONVOLUTION MODEL
# ============================================================

transpose_ae = build_transpose_conv_autoencoder()

transpose_ae.compile(
    optimizer=keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="binary_crossentropy"
)

transpose_ae.fit(
    x_train,
    x_train,
    epochs=20,
    batch_size=128,
    validation_data=(x_test, x_test),
    verbose=1
)

transpose_reconstructed = transpose_ae.predict(
    x_test,
    verbose=0
)

# ============================================================
# CELL 75: TRANSPOSE CONVOLUTION METRICS
# ============================================================

transpose_mse, transpose_mae, transpose_ssim = calculate_metrics(
    x_test,
    transpose_reconstructed
)

print("Transpose Convolution AE")
print("------------------------")
print("MSE :", transpose_mse)
print("MAE :", transpose_mae)
print("SSIM:", transpose_ssim)

# ============================================================
# CELL 76: NOISE COMPARISON
# ============================================================

print("Gaussian Noise Results")
print("======================")
display(noise_df)

print("\nSalt-and-Pepper Results")
print("=======================")
display(sp_df)

# ============================================================
# CELL 77: SAVE ALL TABLES
# ============================================================

comparison.to_csv(
    "FC_vs_CAE.csv",
    index=False
)

noise_df.to_csv(
    "Gaussian_noise_results.csv",
    index=False
)

sp_df.to_csv(
    "Salt_pepper_results.csv",
    index=False
)

latent_df.to_csv(
    "FC_latent_dimension_results.csv",
    index=False
)

conv_latent_df.to_csv(
    "CAE_latent_dimension_results.csv",
    index=False
)

vae_results_table.to_csv(
    "VAE_results.csv",
    index=False
)

print("All result tables saved.")

# ============================================================
# CELL 78: CREATE RESULTS FOLDER
# ============================================================

os.makedirs(
    "autoencoder_results",
    exist_ok=True
)

print("Results directory created.")

# ============================================================
# CELL 79: FINAL CONSOLIDATED TABLE
# ============================================================

print("=" * 80)
print("FINAL AUTOENCODER EXPERIMENT RESULTS")
print("=" * 80)

display(final_results)

print("\nGaussian Noise Results")
display(noise_df)

print("\nFC Latent Dimension Results")
display(latent_df)

print("\nCAE Latent Dimension Results")
display(conv_latent_df)

print("\nVAE Results")
display(vae_results_table)

